/*
 * This source file was generated by the Gradle 'init' task
 */
package biz.digitalindustry.gradleyard;

import java.io.File;
import java.io.IOException;
import java.io.Writer;
import java.io.FileWriter;
import org.gradle.testkit.runner.GradleRunner;
import org.gradle.testkit.runner.BuildResult;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;

/** Functional test for the GradleYard plugin. */
class PublishingPluginPluginFunctionalTest {
    @TempDir
    File projectDir;

    private File getBuildFile() {
        return new File(projectDir, "build.gradle");
    }

    private File getSettingsFile() {
        return new File(projectDir, "settings.gradle");
    }

    @Test void canRunTask() throws IOException {
        writeString(getSettingsFile(), "rootProject.name = 'fixture'");
        writeString(getBuildFile(),
            "plugins {\n" +
            "  id('java')\n" +
            "  id('biz.digitalindustry.gradleyard')\n" +
            "}\n" +
            "group = 'biz.digitalindustry.test'\n" +
            "version = '1.0.0'\n" +
            "publishing {\n" +
            "  publications {\n" +
            "    mavenJava(MavenPublication) { from components.java }\n" +
            "  }\n" +
            "}\n" +
            "centralPublisher {\n" +
            "  tokenName = 'token'\n" +
            "  tokenPassword = 'secret'\n" +
            "}\n"
        );

        // Run the build
        GradleRunner runner = GradleRunner.create();
        runner.forwardOutput();
        runner.withPluginClasspath();
        runner.withArguments("centralBundle");
        runner.withProjectDir(projectDir);
        BuildResult result = runner.build();

        // Verify the result
        assertTrue(new File(projectDir, "build/central-bundle.zip").exists());
        assertTrue(result.getOutput().contains("Central bundle created"));
    }

    private void writeString(File file, String string) throws IOException {
        try (Writer writer = new FileWriter(file)) {
            writer.write(string);
        }
    }
}
