/*
 * This source file was generated by the Gradle 'init' task
 */
package biz.digitalindustry.publish;

import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PublishingPluginPluginTest {
    @Test void pluginRegistersCentralTasksAndExtension() {
        Project project = ProjectBuilder.builder().build();
        project.setVersion("1.0.0");

        project.getPlugins().apply("biz.digitalindustry.publish.gradleyard");

        assertNotNull(project.getExtensions().findByName("centralPublisher"));
        assertNotNull(project.getTasks().findByName("centralBundle"));
        assertNotNull(project.getTasks().findByName("uploadCentralBundle"));
    }
}
